name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build Windows targets
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ensure all necessary targets are installed
      run: rustup target add i686-pc-windows-msvc x86_64-pc-windows-msvc
    - name: Build CLI for win-x86
      run: cd cmdapp && cargo build --release --verbose --target i686-pc-windows-msvc
    - name: Build CLI for win-x64
      run: cd cmdapp && cargo build --release --verbose --target x86_64-pc-windows-msvc
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: vtracer.0.6.4.win-x86
        path: target/i686-pc-windows-msvc/release/vtracer.exe
    - uses: actions/upload-artifact@v3
      with:
        name: vtracer.0.6.4.win-x64
        path: target/x86_64-pc-windows-msvc/release/vtracer.exe

  build-macos:
    name: Build macOS targets
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ensure all necessary targets are installed
      run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
    - name: Build CLI for osx-arm64
      run: cd cmdapp && cargo build --release --verbose --target aarch64-apple-darwin
    - name: Build CLI for osx-x64
      run: cd cmdapp && cargo build --release --verbose --target x86_64-apple-darwin
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: vtracer.0.6.4.osx-arm64
        path: target/aarch64-apple-darwin/release/vtracer
    - uses: actions/upload-artifact@v3
      with:
        name: vtracer.0.6.4.osx-x64
        path: target/x86_64-apple-darwin/release/vtracer
